export enum BusinessEC {
    // Create User
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS",

    // Recovery Password
    EMAIL_NOT_REGISTERED = "EMAIL_NOT_REGISTERED",
    RECOVERY_CODE_INVALID = "RECOVERY_CODE_INVALID",
    RECOVERY_MAX_ATTEMPTS_REACHED = "RECOVERY_MAX_ATTEMPTS_REACHED",
    RECOVERY_CODE_EXPIRED = "RECOVERY_CODE_EXPIRED",
    RECOVERY_CODE_USED = "RECOVERY_CODE_USED",

    // Session Current
    SESSION_TOKEN_INVALID_EXPIRED = "SESSION_TOKEN_INVALID_EXPIRED",
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
    PROFILE_INCOMPLETE = "PROFILE_INCOMPLETE",
    ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",
    ACCOUNT_DELETED = "ACCOUNT_DELETED",
}